apiVersion: v1
kind: ResourceQuota
metadata:
  name: forum-quota
  namespace: forum-namespace
spec:
  hard:
    pods: "5"
    services: "7"
    secrets: "6"
    configmaps: "2"
    persistentvolumeclaims: "0"
    
    requests.cpu: "2"
    requests.memory: "1Gi"
    limits.cpu: "1"
    limits.memory: "1.9Gi"