apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: 
  name: forum-app-db-secrets-external
  namespace: forum-namespace
spec:
  secretStoreRef:
    name: docker-pull-secrets-aws
    kind: ClusterSecretStore

  target:
    name: forum-app-db-secrets
    creationPolicy: Owner

  data:
    - secretKey: DB_USER
      remoteRef:
        key: db-creds-secrets
        property: DB_USER
    
    - secretKey: DB_PASSWORD
      remoteRef:
        key: db-creds-secrets
        property: DB_PASSWORD

    - secretKey: DB_NAME
      remoteRef:
        key: db-creds-secrets
        property: DB_NAME
      
    - secretKey: DB_HOST
      remoteRef:
        key: db-creds-secrets
        property: DB_HOST
