apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: 
  name: forum-app-django-secrets-external
  namespace: forum-namespace
spec:
  secretStoreRef:
    name: docker-pull-secrets-aws
    kind: ClusterSecretStore

  target:
    name: forum-app-django-secrets
    creationPolicy: Owner

  data:
    - secretKey: DJANGO_SECRET_KEY
      remoteRef:
        key: django-app-secrets
        property: DJANGO_SECRET_KEY