apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-webapp
  
  namespace: forum-namespace
  
  labels:
    tier: prod
    app: forum
spec:
  selector:
    matchLabels:
      app: forum-webapp

  replicas: 1
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: forum-webapp

    spec:
      containers:
      - name: forum-webapp
        image: mikalaytsepl/forum-app-repo:1.3
        
        envFrom:
          - configMapRef: 
              name: forum-configmap

          - secretRef:
              name: forum-app-db-secrets

        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"

          limits: 
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000

      imagePullSecrets:
      - name: dockerhub-pull-secret
      imagePullPolicy: 



---
apiVersion: v1
kind: Service
metadata:
  name: forum-webapp-service
  namespace: forum-namespace
spec:
  type: ClusterIP
  selector:
    app: forum-webapp
  ports:
  - port: 8000
    targetPort: 8000
