apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: image-pull-external-secret
  namespace: forum-namespace
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: docker-pull-secrets-aws
    kind: ClusterSecretStore

  target:
    name: dockerhub-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson

  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: forum-container-pull-creds
