apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: docker-pull-secrets-aws
  namespace: forum-namespace
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso-irsa
            namespace: external-secrets
